name: Update AFL Ladders

on:
  schedule:
    # Run twice daily during AFL season (9 AM and 9 PM AEST)
    # This covers post-game updates without excessive runs
    - cron: '0 11,23 * * *'  # 11 UTC = 9 PM AEST, 23 UTC = 9 AM AEST
  workflow_dispatch: # Allow manual triggers

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write  # Allow writing to repository contents

jobs:
  update-ladders:
    runs-on: ubuntu-latest
    
    # Only run during AFL season (March-October)
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.schedule && github.event.repository.default_branch == 'master') }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'  # Cache npm dependencies for faster builds
        
    - name: Install dependencies
      run: npm ci --only=production --no-audit
      
    - name: Fetch latest ladder data
      run: node scripts/scrape-ladders.js
      
    - name: Save import timestamp
      run: |
        echo "{\"lastUpdated\": \"$(date -u '+%Y-%m-%dT%H:%M:%S.000Z')\"}" > public/data/last-updated.json
        echo "Timestamp saved: $(date -u '+%Y-%m-%d %H:%M UTC')"
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain public/data/)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected in ladder data"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add public/data/afl.json public/data/aflw.json public/data/last-updated.json
        git commit -m "Update AFL ladder data - $(date -u '+%Y-%m-%d %H:%M UTC')"
        git push
        echo "✅ Ladder data updated and pushed"
